export const ROLE_PERMISSIONS = {
  admin: {
    label: 'Líder del Restaurante',
    color: '#e8453c',
    // Gestión general
    canManageUsers: true,
    canManageReservations: true,
    canViewReports: true,
    canManageClients: true,
    canManageTables: true,
    canViewAllReservations: true,
    canCancelAnyReservation: true,
    canConfigureSystem: true,
    canViewIncomesChart: true,
    canViewAdminDashboard: true,
    canManageAllUsers: true,
    canExportData: true,
    // Caja
    canViewCash: true,
    canManageCash: true,
    // Cocina
    canViewKitchen: true,
    canManageKitchenOrders: true,
    // Acciones exclusivas del admin/líder
    canDeleteClients: true,
    canDeleteReservations: true,
    canSeatGuests: true,
    canManageMenu: true,
    // IA y Agentes — SOLO el líder
    canViewAgents: true,
    canViewAssistant: true,
    canViewComplaints: true,
    canViewAudit: true,
    canViewSecurity: true,
    // Modificar items de pedidos ya enviados a cocina
    canModifyOrderItems: true,
    // Modificar datos de clientes
    canEditClients: true,
  },

  cajero: {
    label: 'Cajero/a',
    color: '#e67e22',
    canManageUsers: false,
    canManageReservations: true,
    canViewReports: true,
    canManageClients: false,
    canManageTables: false,
    canViewAllReservations: true,
    canCancelAnyReservation: true,
    canConfigureSystem: false,
    canViewIncomesChart: false,
    canViewAdminDashboard: false,
    canManageAllUsers: false,
    canExportData: false,
    canViewCash: true,
    canManageCash: true,
    canManageKitchenOrders: false,
    canViewKitchen: false,
    canDeleteClients: false,
    canDeleteReservations: false,
    canSeatGuests: false,
    // IA — NO
    canViewAgents: false,
    canViewAssistant: false,
    canViewComplaints: false,
    canViewAudit: false,
    canViewSecurity: false,
    // Puede modificar items de pedidos
    canModifyOrderItems: true,
    canEditClients: false,
  },
  hostess: {
    label: 'Anfitriona de Bienvenida',
    color: '#8e44ad',
    canManageUsers: false,
    canManageReservations: true,
    canViewReports: false,
    canManageClients: false,
    canManageTables: true,
    canViewAllReservations: true,
    canCancelAnyReservation: false,
    canConfigureSystem: false,
    canViewIncomesChart: false,
    canViewAdminDashboard: false,
    canManageAllUsers: false,
    canExportData: false,
    canViewCash: false,
    canManageCash: false,
    canManageKitchenOrders: false,
    canViewKitchen: false,
    canDeleteClients: false,
    canDeleteReservations: false,
    canSeatGuests: true,
    // IA — NO
    canViewAgents: false,
    canViewAssistant: false,
    canViewComplaints: false,
    canViewAudit: false,
    canViewSecurity: false,
    // Solo agregar, NO quitar items
    canModifyOrderItems: false,
    canEditClients: false,
  },
  mozo: {
    label: 'Mozo/a',
    color: '#27ae60',
    canManageUsers: false,
    canManageReservations: false,
    canViewReports: false,
    canManageClients: false,
    canManageTables: false,
    canViewAllReservations: false,
    canCancelAnyReservation: false,
    canConfigureSystem: false,
    canViewIncomesChart: false,
    canViewAdminDashboard: false,
    canManageAllUsers: false,
    canExportData: false,
    canViewCash: false,
    canManageCash: false,
    canManageKitchenOrders: false,
    canViewKitchen: false,
    canDeleteClients: false,
    canDeleteReservations: false,
    canSeatGuests: false,
    // IA — NO
    canViewAgents: false,
    canViewAssistant: false,
    canViewComplaints: false,
    canViewAudit: false,
    canViewSecurity: false,
    // Solo agregar, NO quitar items
    canModifyOrderItems: false,
    canEditClients: false,
  },
  jefe_cocina: {
    label: 'Jefe de Cocina',
    color: '#e67e22',
    canManageUsers: false,
    canManageReservations: false,
    canViewReports: false,
    canManageClients: false,
    canManageTables: false,
    canViewAllReservations: true,
    canCancelAnyReservation: false,
    canConfigureSystem: false,
    canViewIncomesChart: false,
    canViewAdminDashboard: false,
    canManageAllUsers: false,
    canExportData: false,
    canViewCash: false,
    canManageCash: false,
    canViewKitchen: true,
    canManageKitchenOrders: true,
    canDeleteClients: false,
    canDeleteReservations: false,
    canSeatGuests: false,
    // IA — NO
    canViewAgents: false,
    canViewAssistant: false,
    canViewComplaints: false,
    canViewAudit: false,
    canViewSecurity: false,
    canModifyOrderItems: false,
    canEditClients: false,
  },
}
